version: "3.7"

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-none-dev


  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    env_file:
      - .env-none-dev
    ports:
      - 9999:8000
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    env_file:
      - .env-none-dev
  flower:
    build:
      context: .
    container_name: flower_app
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
    env_file:
      - .env-none-dev
